version: "3"
services:
  api-flask:
    build: .
    image: nfe-reader/base
    environment: 
      - FLASK_APP=run.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - SERVER_NAME="0.0.0.0"
    command: 
      - "flask"
      - "run"
      - "--host=0.0.0.0"
    ports: 
      - "5051:5000"
    volumes: 
      - "./:/usr/src/app"
  api-gunicorn:
    build: .
    image: nfe-reader/base
    command: gunicorn api.app:create_app() -w 4 -b 0.0.0.0:5000
    ports: 
      - "5052:5000"
    volumes: 
      - "./:/usr/src/app"
  crawler:
    build: .
    image: nfe-reader/base
    entrypoint: python local_run.py
    volumes: 
      - "./:/usr/src/app"